language: csharp
mono: none
dist: xenial
dotnet: 2.2
script:
 - dotnet publish
 - dotnet test *xunit* -c Release /p:CollectCoverage=true	/p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*"
 - dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools
 - tools/reportgenerator -reports:dep-check-xunit/coverage.opencover.xml -targetdir:report -verbosity:Warning
